/* Generated By:JavaCC: Do not edit this line. mas2jConstants.java */
package jason.mas2j.parser;

public interface mas2jConstants {

  int EOF = 0;
  int MAS = 7;
  int AGS = 8;
  int ENV = 9;
  int CONTROL = 10;
  int AT = 11;
  int INFRA = 12;
  int CLASSPATH = 13;
  int SOURCEPATH = 14;
  int ASOEE = 15;
  int ASOEEV = 16;
  int ASOIB = 17;
  int ASOIBV = 18;
  int ASONRC = 19;
  int ASOV = 20;
  int DIRECTIVE = 21;
  int ASOSYNC = 22;
  int ASOBOOL = 23;
  int ASAGCLASS = 24;
  int ASAGARCHCLASS = 25;
  int BBCLASS = 26;
  int NUMBER = 27;
  int STRING = 28;
  int ASID = 29;
  int ID = 30;
  int PATH = 31;
  int DRIVER = 32;
  int LETTER = 33;
  int LC_LETTER = 34;
  int UP_LETTER = 35;
  int DIGIT = 36;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"MAS\"",
    "\"agents\"",
    "\"environment\"",
    "\"executionControl\"",
    "\"at\"",
    "\"infrastructure\"",
    "\"classpath\"",
    "\"aslSourcePath\"",
    "\"events\"",
    "<ASOEEV>",
    "\"intBels\"",
    "<ASOIBV>",
    "\"nrcbp\"",
    "\"verbose\"",
    "\"directives\"",
    "\"synchronised\"",
    "<ASOBOOL>",
    "\"agentClass\"",
    "\"agentArchClass\"",
    "\"beliefBaseClass\"",
    "<NUMBER>",
    "<STRING>",
    "<ASID>",
    "<ID>",
    "<PATH>",
    "<DRIVER>",
    "<LETTER>",
    "<LC_LETTER>",
    "<UP_LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\"#\"",
    "\";\"",
    "\".\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
  };

}
