/* Generated By:JavaCC: Do not edit this line. as2jConstants.java */
package jason.asSyntax.parser;

public interface as2jConstants {

  int EOF = 0;
  int VAR = 7;
  int TK_TRUE = 8;
  int TK_FALSE = 9;
  int TK_NOT = 10;
  int TK_NEG = 11;
  int TK_INTDIV = 12;
  int TK_INTMOD = 13;
  int TK_BEGIN = 14;
  int TK_END = 15;
  int TK_LABEL_AT = 16;
  int TK_IF = 17;
  int TK_ELSE = 18;
  int TK_FOR = 19;
  int TK_WHILE = 20;
  int TK_PAND = 21;
  int TK_POR = 22;
  int NUMBER = 23;
  int STRING = 24;
  int ATOM = 25;
  int UNNAMEDVAR = 26;
  int CHAR = 27;
  int LETTER = 28;
  int LC_LETTER = 29;
  int UP_LETTER = 30;
  int DIGIT = 31;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<VAR>",
    "\"true\"",
    "\"false\"",
    "\"not\"",
    "\"~\"",
    "\"div\"",
    "\"mod\"",
    "\"begin\"",
    "\"end\"",
    "\"@\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"while\"",
    "\"|&|\"",
    "\"|||\"",
    "<NUMBER>",
    "<STRING>",
    "<ATOM>",
    "<UNNAMEDVAR>",
    "<CHAR>",
    "<LETTER>",
    "<LC_LETTER>",
    "<UP_LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\":-\"",
    "\".\"",
    "\"!\"",
    "\":\"",
    "\"<-\"",
    "\"+\"",
    "\"-\"",
    "\"^\"",
    "\"?\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"!!\"",
    "\"<\"",
    "\">\"",
    "\"::\"",
    "\",\"",
    "\"[\"",
    "\"|\"",
    "\"]\"",
    "\"&\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"\\\\==\"",
    "\"=\"",
    "\"=..\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
  };

}
